apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.job_core_service_app_name }}
spec:
  selector:
    app: {{ .Values.job_core_service_app_name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080