job_core_service_app_name: job-core-service
containers:
  job_core_service_image: registry.gitlab.com/vegaproject/job-core-service/image:latest
db:
  url: jdbc:postgresql://postgresql-dev:5432/job_core_service
  user: postgres
  pass: wmuljGyLs0
kafka:
  url: kafka:9092
keycloak:
  issuer: http://keycloak:8180/auth/realms/quarkus
  url: http://keycloak:8180/auth
  realm: vacancinated
  client_id: frontend-service
replicas:
  count: 1