apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.job_core_service_app_name }}
  labels:
    app: {{ .Values.job_core_service_app_name }}
spec:
  replicas: {{ .Values.replicas.count }}
  selector:
    matchLabels:
      app: {{ .Values.job_core_service_app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.job_core_service_app_name }}
    spec:
      imagePullSecrets:
      - name: gitlab-registry-key
      containers:
      - name: {{ .Values.job_core_service_app_name }}
        image: {{ .Values.containers.job_core_service_image }}
        ports:
        - containerPort: 8090
        env:
          - name: KAFKA_URL
            value: {{ .Values.kafka.url }}
          - name: DB_URL
            value: {{ .Values.db.url }}
          - name: KEYCLOAK_ISSUER
            value: {{ .Values.keycloak.issuer }}